{{ if .Values.global.tls.custom_cert }}
---
apiVersion: v1
kind: Secret
metadata:
    name: ingress-cert
type: Opaque
data:
  ca.crt: {{ .Values.global.tls.ca | b64enc }}
  tls.crt: {{ .Values.global.tls.tkeyls | b64enc }}
{{ end }}