{{ if .Values.global.tls.custom_cert }}
---
apiVersion: v1
kind: Secret
metadata:
    name: ingress-cert
type: Opaque
data:
  ca.crt: {{ .Values.global.tls.ca  }}
  tls.crt: {{ .Values.global.tls.tkeyls }}
{{ end }}