{{ if eq .Values.global.persistence.type "PVC" }}

{{- $fullName := include "dcm4che-logstash.fullname" . -}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $fullName }}-{{ .Values.volume.name }}
spec:
  storageClassName: {{ $.Values.global.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.size }}
{{ end }}