---
apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - protocol: TCP
      port: 80
      name: web
      targetPort: 80
      nodePort: {{ .Values.ports.http }}
    - protocol: TCP
      port: 443
      name: websecure
      targetPort: 443
      nodePort: {{ .Values.ports.https }}      
    - protocol: TCP
      port: 8100
      name: traefik
      targetPort: 8100
      nodePort: {{ .Values.ports.dashboard }}      
    # - protocol: TCP
    #   port: 8080
    #   name: admin
    #   targetPort: 8080
    #   nodePort: 30900
    # - protocol: TCP
    #   port: 8000
    #   name: tcpep
    #   targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: traefikudp
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - protocol: UDP
      port: 9000
      name: udpep
      targetPort: 9000


---
apiVersion: v1
kind: Service
metadata:
  name: traefikhl7
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - protocol: TCP
      name: hl7
      port: 2575
      targetPort: 2575
      nodePort: {{ .Values.ports.hl7 }}


---
apiVersion: v1
kind: Service
metadata:
  name: traefikhl7-udp
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:      
    - protocol: UDP
      name: hl7-udp
      port: 2575
      targetPort: 2575
      nodePort: {{ .Values.ports.hl7udp }}   

---
apiVersion: v1
kind: Service
metadata:
  name: traefikdicom
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:      
    - protocol: TCP      
      name: dicom
      port: 2762
      targetPort: 2762
      nodePort: {{ .Values.ports.dicom }}

---
apiVersion: v1
kind: Service
metadata:
  name: traefiknema
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:      
    - protocol: TCP      
      name: nema
      port: 11112
      targetPort: 11112
      nodePort: {{ .Values.ports.nema }}