{{- if .Values.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dcm4che-gatekeeper.fullname" . }}
  labels:
    {{- include "dcm4che-gatekeeper.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dcm4che-gatekeeper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dcm4che-gatekeeper.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- range $arg := .Values.args }}
            - {{ $arg }}
            {{- end}}
          ports:
            {{- range $port :=  .Values.service.ports }}
            - containerPort: {{ $port.number }}
              protocol: {{ $port.protocol }}
            {{- end}}  
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          env:
            {{- range $key, $val := .Values.env_vars }}
            - name: {{ $key }}
              value: {{ $val | quote}}
            {{- end}}
            - name: PROXY_REDIRECTION_URL
              value: "https://kibana.{{ .Values.global.domain }}:30443"
            - name: PROXY_DISCOVERY_URL
              value: "https://keycloak.{{ .Values.global.domain }}:30443/auth/realms/dcm4che"
            - name: PROXY_CLIENT_SECRET
              value: "{{ .Values.keycloak.client_secret }}"
          # volumeMounts:
          # - name: vm-localtime
          #   mountPath: /etc/localtime            
          # - name: vm-timezone
          #   mountPath: /etc/timezone 
          # - name: data
          #   mountPath: /opt/gatekeeper/standalone            
          resources:
            {{- toYaml .Values.resources | nindent 12 }}          
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      # volumes:
      #   - name: vm-localtime
      #     hostPath:
      #       path: /etc/localtime  
      #   - name: vm-timezone
      #     hostPath:
      #       path: /etc/timezone  
      #   {{- range $volume :=  .Values.volumes }}
      #   - name: {{ $volume.name }}
      #     {{ $volume.type }}:          
      #     {{- range $key, $val := $volume.properties }}
      #       {{$key}}: {{ $val | quote}}
      #     {{- end}}  
      #   {{- end}}  
{{- end}}