{{- if .Values.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dcm4che-gatekeeper.fullname" . }}
  labels:
    {{- include "dcm4che-gatekeeper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports: 
    {{- range $port :=  .Values.service.ports }}
    - name: {{ $port.name }}
      port: {{ $port.number }}
      targetPort: {{ $port.number }}
      protocol: {{ $port.protocol }}
    {{- end}}
  selector:
    {{- include "dcm4che-gatekeeper.selectorLabels" . | nindent 4 }}
{{- end}}