{{ if .Values.global.tls.custom_cert }}
---
apiVersion: v1
kind: Secret
metadata:
    name: ingress-pem
type: Opaque
data:
  privkey.pem: {{ .Values.global.tls.privkey | b64enc }}
  fullchain.pem: {{ .Values.global.tls.fullchain | b64enc }}
{{ end }}