{{- if .Values.ingress.enabled -}}

{{- $fullName := include "dcm4che-pacs.fullname" . -}}


# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: {{ $fullName }}-http
# spec:
#   entryPoints:
#     - web
#   routes:
#   {{- range .Values.ingress.hosts.nonTLS }}  
#   - match: Host(`{{ .host }}.{{ $.Values.global.domain }}`)
#     kind: Rule
#     services:
#     - name:  {{ .service }}
#       port: {{ .port }}

#   {{- end }}


{{- if .Values.ingress.withTLS }}

# ---

# # Create cert
# apiVersion: cert-manager.io/v1alpha2
# kind: Issuer
# metadata:
#   name: {{ $fullName }}
# spec:
#   selfSigned: {}
# ---
# apiVersion: cert-manager.io/v1alpha2
# kind: Certificate
# metadata:
#   name: {{ $fullName }}-cert
# spec:
#   commonName: {{ $fullName }}
#   secretName: {{ $fullName }}-cert
#   issuerRef:
#     name: {{ $fullName }}
#   dnsNames: 
#   {{- range .Values.ingress.hosts.TLS }}  
#   - {{ .host }}.{{ $.Values.global.domain }}
#   {{- end}}


---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: pacs-rate
spec:
  rateLimit:
    average: 100
    burst: 50

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: pacs-compress
spec:
  compress: {}

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: pacs-prefix
spec:
  addPrefix:
    prefix: /dcm4chee-arc/ui2        

---   

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-https
spec:
  entryPoints:
    - websecure
  routes:
  {{- range .Values.ingress.hosts.TLS }}  
  - match: Host(`{{ .host }}{{ $.Values.global.domain }}`)
    kind: Rule
    middlewares:
    - name: pacs-rate    
    #- name: pacs-prefix
    - name: pacs-compress
    services:
    - name:  {{ .service }}
      port: {{ .port }}
      scheme: https
  {{- end }}
  tls:
    hosts: 
    {{- range .Values.ingress.hosts.TLS }}      
      - {{ .host }}{{ $.Values.global.domain }}
    {{- end}}
    passthrough: false
    options:
      name: keycloak-tls-options
{{- end}}

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $fullName }}-nema
spec:
  entryPoints:
    - nema
  routes:
  {{- range .Values.ingress.hosts.TLS }}  
  - match: HostSNI(`*`)
    kind: Rule
    services:
    - name:  {{ .service }}
      port: 11112
      scheme: tcp
  {{- end }}


# DICOM port
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $fullName }}-dicom
spec:
  entryPoints:
    - dicom
  routes:
  {{- range .Values.ingress.hosts.TLS }}  
  - match: HostSNI(`*`)
    kind: Rule
    services:
    - name:  {{ .service }}
      port: 2762
      scheme: tcp
  {{- end }}
  
# HL7
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $fullName }}-hl7
spec:
  entryPoints:
    - hl7
  routes:
  {{- range .Values.ingress.hosts.TLS }}  
  - match: HostSNI(`*`)
    kind: Rule
    services:
    - name:  {{ .service }}
      port: 2575
      scheme: tcp
  {{- end }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: {{ $fullName }}-hl7-udp
spec:
  entryPoints:
    - hl7udp
  routes:
  {{- range .Values.ingress.hosts.TLS }}  
  - match: HostSNI(`*`)
    kind: Rule
    services:
    - name:  {{ .service }}
      port: 2575
      scheme: udp
  {{- end }}  

{{- end}}

