{{- if .Values.ingress.enabled -}}

{{- $fullName := include "dcm4che-pacs.fullname" . -}}

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-http
spec:
  entryPoints:
    - web
  routes:
  {{- range .Values.ingress.hosts.nonTLS }}  
  - match: Host(`{{ .host }}.{{ $.Values.global.domain }}`)
    kind: Rule
    services:
    - name:  {{ .service }}
      port: {{ .port }}

  {{- end }}


{{- if .Values.ingress.withTLS }}

---

# Create cert
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ $fullName }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ $fullName }}-cert
spec:
  commonName: {{ $fullName }}
  secretName: {{ $fullName }}-cert
  issuerRef:
    name: {{ $fullName }}
  commonName: {{ .host }}.{{ $.Values.global.domain }}
---   

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}-https
spec:
  entryPoints:
    - websecure
  routes:
  {{- range .Values.ingress.hosts.TLS }}  
  - match: Host(`{{ .host }}.{{ $.Values.global.domain }}`)
    kind: Rule
    services:
    - name:  {{ .service }}
      port: {{ .port }}
      scheme: https

  {{- end }}
  tls:
    secretName: {{ $fullName }}-cert
    hosts: {{ .host }}.{{ $.Values.global.domain }}

{{- end}}
{{- end}}


