
# Tomando como ejemplo hospital.test.com para el nombre de dominio
# Se generan las siguientes rutas en el ingress
#   - kibana-pacshospital.test.com
#   - keycloak-pacshospital.test.com
#   - visorhospital.test.com
#   - pacshospital.test.com
#   - console-pacshospital.test.com


# No cambiar el prefix
global:
  prefix: dcm4che
  domain: hpn.andes.gob.ar
  https_port: 30443

  persistence:
    enabled: true
    type: "PVC"
    storageClass: ""
    # path: "/k8s"
  tls:
    custom_cert: true
    ca: "-empty-"
    # key: "-empty-"
    
# Fluentbit
fluent-bit:
  enabled: true
  backend:
    type: "http"
    http:
      host: dcm4che-logstash
      port: 8080
      format: json

  
dcm4che-gatekeeper:
  enabled: false
  keycloak:
    client_secret: ''

