
# No cambiar el prefix
global:
  prefix: dcm4che
  domain: smart.192-168-0-8.nip.io
  

# Fluentbit
fluent-bit:
  enabled: True
  backend:
    type: "forward"
    forward:
      host: "dcm4che-logstash"
      port: 12201

  
gatekeeper:
  enabled: False
  keycloak:
    client_secret: ''

