
# No cambiar el prefix
global:
  prefix: dcm4che
  domain: smart.andes.gob.ar
    
# Fluentbit
fluent-bit:
  enabled: true
  backend:
    type: "forward"
    forward:
      host: "dcm4che-logstash"
      port: 12201

  
dcm4che-gatekeeper:
  enabled: false
  keycloak:
    client_secret: ''

