---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "traefik.fullname" . }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}    

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "traefik.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "traefik.fullname" . }}
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443              
            - name: dashboard
              containerPort: 8100             

          volumeMounts:
          {{- if .Values.tls.custom_cert }}
            - name: certificates
              mountPath: /certs
              readOnly: true
          {{- end }}
            - name: config-files-static
              mountPath: /etc/traefik/traefik.yaml
              subPath: traefik.yaml
              readOnly: true      
            - name: config-files
              mountPath: /config
              readOnly: true                        
      volumes:
      {{- if .Values.tls.custom_cert }}
      - name: certificates
        secret:
          secretName: traefik-default-certs     
      {{- end }}
      - name: config-files
        configMap:
          name: "traefik-config"      
      - name: config-files-static
        configMap:
          name: "traefik-config-static"                        

