---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "traefik.fullname" . }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}    

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "traefik.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "traefik.fullname" . }}
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            # - --log.level=DEBUG
            #- --log.format=json
            # - --api
            # - --api.insecure
            # - --entryPoints.traefik.address=:8100
            # - --entrypoints.web.address=:80
            # - --entrypoints.websecure.address=:443
            
            # - --entrypoints.tcp.address=:8000
            # - --entrypoints.udp.address=:9000/udp
            # - --entrypoints.hl7.address=:2575
            # - --entrypoints.hl7.address=:2575/udp
            # - --entrypoints.dicom.address=:2762
          
            # - --providers.kubernetescrd
            # - --providers.kubernetesingress=true
            # - --api.debug=true
            #- --providers.kubernetescrd.namespaces=default,dcm4che
            # - --serversTransport.insecureSkipVerify=true
            # - --certificatesresolvers.default.acme.tlschallenge
            # - --certificatesresolvers.default.acme.email=orlando.brea@gmail.com
            # - --certificatesresolvers.default.acme.storage=acme.json
            # - --configFile=/config/static/config.yaml
            # - --providers.file.directory=/config/dynamic/
            # - --providers.file.watch=true
            # - --certificatesresolvers.default.acme.tlschallenge
            # - --certificatesresolvers.default.acme.email=foo@you.com
            # - --certificatesresolvers.default.acme.storage=acme.json
            # Please note that this is the staging Let's Encrypt server.
            # Once you get things working, you should remove that whole line altogether.
            #- --certificatesresolvers.default.acme.caserver=https://step-certificates/directory
            # - --tracing=true
            # - --tracing.zipkin=true
            # - --tracing.zipkin.httpEndpoint=http://192.168.0.8:9411/api/v2/spans
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443              
            - name: dashboard
              containerPort: 8100             

          volumeMounts:
          {{- if .Values.tls.custom_cert }}
            - name: certificates
              mountPath: /certs
              readOnly: true
          {{- end }}
            - name: config-files-static
              mountPath: /etc/traefik/traefik.yaml
              subPath: traefik.yaml
              readOnly: true      
            - name: config-files
              mountPath: /config
              readOnly: true                        
      volumes:
      {{- if .Values.tls.custom_cert }}
      - name: certificates
        secret:
          secretName: traefik-default-certs     
      {{- end }}
      - name: config-files
        configMap:
          name: "traefik-config"      
      - name: config-files-static
        configMap:
          name: "traefik-config-static"                        

