{{- if .Values.enabled }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "traefik.fullname" . }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}    

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "traefik.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "traefik.fullname" . }}
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --log.level=DEBUG
            #- --log.format=json
            - --api
            - --api.insecure
            - --entryPoints.traefik.address=:8100
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            
            - --entrypoints.tcpep.address=:8000
            - --entrypoints.udpep.address=:9000/udp
            - --entrypoints.hl7.address=:2575
            - --entrypoints.hl7.address=:2575/udp
            - --entrypoints.dicom.address=:2762
          
            - --providers.kubernetescrd
            - --providers.kubernetesingress=true
            - --api.debug=true
            #- --providers.kubernetescrd.namespaces=default,dcm4che
            - --serversTransport.insecureSkipVerify=true
            - --certificatesresolvers.default.acme.tlschallenge
            - --certificatesresolvers.default.acme.email=orlando.brea@gmail.com
            - --certificatesresolvers.default.acme.storage=acme.json
            # - --certificatesresolvers.default.acme.tlschallenge
            # - --certificatesresolvers.default.acme.email=foo@you.com
            # - --certificatesresolvers.default.acme.storage=acme.json
            # Please note that this is the staging Let's Encrypt server.
            # Once you get things working, you should remove that whole line altogether.
            #- --certificatesresolvers.default.acme.caserver=https://step-certificates/directory
            # - --tracing=true
            # - --tracing.zipkin=true
            # - --tracing.zipkin.httpEndpoint=http://192.168.0.8:9411/api/v2/spans
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443              
            - name: traefik-admin
              containerPort: 8100              
            - name: admin
              containerPort: 8080
            - name: tcpep
              containerPort: 8000
            - name: udpep
              containerPort: 9000
            - name: hl7
              containerPort: 2575
            - name: dicom
              containerPort: 2762

{{- end-}}