---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dcm4che-ohif.fullname" . }}
  labels:
    {{- include "dcm4che-ohif.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dcm4che-ohif.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dcm4che-ohif.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range $port :=  .Values.service.ports }}
            - containerPort: {{ $port.number }}
              protocol: {{ $port.protocol }}
            {{- end}}  
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          volumeMounts:
          - name: config-files
            mountPath: /usr/share/nginx/html/app-config.js
            subPath: default.js
            readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}          
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: config-files
          configMap:
            name: "ohif-configmap"