{{- $fullName := include "dcm4che-elastic.fullname" . -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "dcm4che-elastic.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dcm4che-elastic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dcm4che-elastic.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range  .Values.service.ports }}
            - containerPort: {{ .number }}
              protocol: {{ .protocol }}
            {{- end}}            
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          env:
            {{- range $key, $val := .Values.env_vars }}
            - name: {{ $key }}
              value: {{ $val | quote}}
            {{- end}}
          volumeMounts:
          - name: vm-localtime
            mountPath: /etc/localtime            
          - name: vm-timezone
            mountPath: /etc/timezone   
          - name: data
            mountPath: /usr/share/elasticsearch/data                       
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}        
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: vm-localtime
          hostPath:
            path: /etc/localtime  
        - name: vm-timezone
          hostPath:
            path: /etc/timezone   
        - name: {{ .Values.volumes.name }}
          {{ if eq $.Values.global.persistence.type "PVC" }}
          persistentVolumeClaim:
            claimName: {{ $fullName }}-{{ .Values.volumes.name }}
          {{ end }}
          {{ if eq $.Values.global.persistence.type "PATH" }}
          hostPath:
            path: {{ $.Values.global.persistence.path }}{{ .Values.volumes.path }}
            type: DirectoryOrCreate
          {{ end }}
