{{- $fullName := include "dcm4che-elastic.fullname" . -}}

{{ if eq .Values.global.persistence.type "PVC" }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "algo-{{ .Values.volume.name }}"
spec:
  storageClassName: {{ $.Values.global.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.size }}

{{ end }}