{{- $fullName := include "dcm4che-elastic.fullname" . -}}

{{- if eq .Values.global.persistence.type "PVC" }}

{{- range $volume :=  .Values.volumes }}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $fullName }}-v{{ $volume.name }}
spec:
  storageClassName: {{ $.Values.global.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $volume.size }}

{{- end }}

{{- end }}