{{- $fullName := include "dcm4che-elastic.fullname" . -}}


{{- range .Values.volumes }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "algo-{{ .name }}"
spec:
  storageClassName: {{ $.Values.global.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
