apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.prefix }}-{{ include "whoami.fullname" . }}
  labels:
    {{- include "whoami.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports: 
    {{- range $port :=  .Values.service.ports }}
    - name: {{ $port.name }}
      port: {{ $port.number }}
      targetPort: {{ $port.number }}
      protocol: {{ $port.protocol }}
    {{- end}}
  selector:
    {{- include "whoami.selectorLabels" . | nindent 4 }}
